name: Java CI

on:
  push:
    branches:
      - KhanbanTasks
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up JDK 17
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt-openjdk'  # Make sure this is the correct distribution (adopt-openjdk is now Eclipse Temurin)

    # Step 3: Build with Maven and install dependencies
    - name: Build with Maven
      run: mvn clean install -DskipTests=false  # Ensures tests are executed during the build phase

    # Step 4: Run tests
    - name: Run Tests
      run: mvn test  # Ensure tests are explicitly run, even if already executed in the previous step.

    # Optional: Upload test results (if you want to visualize test results)
    - name: Upload test results
      if: always()  # Ensures this step runs even if previous steps fail
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: target/test-classes  # Adjust this path depending on where your test reports are generated
